### ISSUE TITLE
ЧПУ ссылок

### ISSUE THREAD

**Issue by galstudio** [dveezhok/EngineCMS#37]
При попытке установить транслит ссылок в чпу пишет ошибку Parse error: syntax error, unexpected T_VARIABLE in /home/alex/htdocs/test.ru/www/engine/clean_url.php on line 16

**Comment by dveezhok** [comment]
свежая версия Движка?




____________С уважением,Влад Мерк.

**Comment by galstudio** [comment]
да, пару часов с сайта скачал, решил потестить на локалке... и вот :(

**Comment by dveezhok** [comment]
без чпу отлично работает, а ошибку эту проверю - отпишусь




____________С уважением,Влад Мерк.

**Comment by dveezhok** [comment]
исправлено
