### ISSUE TITLE
ЧПУ

### ISSUE THREAD

**Issue by yuri25** [dveezhok/EngineCMS#39]
http://engine/about_me/

Parse error: syntax error, unexpected 'if' (T_IF) in C:\OpenServer\domains\engine\engine\clean_url.php on line 16

И так по любым адресам из верхнего меню

**Comment by dveezhok** [comment]
- исправлено ЧПУ
- исправлена ошибка с кешированием главной страницы администрирования
- исправлено кеширование ЧПУ-страниц, в том числе русскоязычных
обновил
