### ISSUE TITLE
ЧПУ и отображение лого сайта

### ISSUE THREAD

**Issue by yuri25** [dveezhok/EngineCMS#41]
При включенном ЧПУ неправильно обрабатывается лого сайта, картинка видна только на главной странице, при переходе по ссылкам меню картинка пропадает т.к. в УРЛ добавляется название раздела типа такого http://engine/notes/img/logotip.png

**Comment by dveezhok** [comment]
Как вариант - изменить адрес логотипа сайта в дизайне на абсолютный — http://engine/img/logotip.png
Или речь о логотипе, который ставится автоматическим блоком?

**Comment by yuri25** [comment]
Речь идет об этой картинке http://engine/img/logotip.png  Прописал в админке http://engine/img/logotip.png  вместо img/logotip.png  - теперь все работает. Спасибо.

**Comment by dveezhok** [comment]
На будущее доработаю. Спасибо за баги!
